// <auto-generated />
namespace WebShop2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedorders : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedorders));
        
        string IMigrationMetadata.Id
        {
            get { return "201803261428595_added-orders"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
