// <auto-generated />
namespace WebShop2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class inputvirtualfieldfix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(inputvirtualfieldfix));
        
        string IMigrationMetadata.Id
        {
            get { return "201803270900097_input-virtual-field-fix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
